### PR TITLE
Added files

### PR DESCRIPTION
**Pull request by Naoki95957**
This has all the files for the 2015 CAD on homedirs to date. All it needs is the merge ☺

### CODE REVIEW

**Comment by endreman0** [comment]
That's a lot! Are any of those produced by National Instruments, Vex, etc? If so, I suggest we use a `.gitignore` to get rid of them. We have a 1GB limit, and filling it with models you can find online seems like a waste of space.

**Comment by Naoki95957** [comment]
Yes, I think there are a handful of models that are designed by us (you'll have go around and ask, idk all of them, however I imagine any model with color probably isn't ours xD). Also, I'm pretty sure you can go over 1GB, you'll just get an email politely recommending you upgrade or stay away from large uploads again xP.

-------- Original message --------

**Comment by Naoki95957** [comment]
Currently there's 1.44GB's of data uploaded

-------- Original message --------

**Comment by endreman0** [comment]
I think Github should be famous for their polite emails. Oversized repositories, Github Pages build failures, introduction to Github - it's awesome!
Still, we need to shrink that repo. I'll pull it at some point (when I can afford not using my computer for an hour while it downloads), gitignore it, and put it back up.

**Comment by endreman0** [comment]
I compressed the repository. I don't now how you read the size, but it's about 88% of what it was in number of files. If each file is the same size, we're just under 1GB, but I doubt it.
TIL Github renders STL files. Keep up the awesomeness, Github.

**Comment by Naoki95957** [comment]
Ikr! I saw the stl's protected in wire, surface and full and simply flipped over. XD the only reason I knew the size is cause I had to sit and watch it upload as well as copy the files.

-------- Original message --------

**Pull request merged**
